apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - nfs-server-v3.yaml
  - nfs-server-v41.yaml
  - nfs-server-v42.yaml
  - nfs-server-tls-secret.yaml
  - nfs-server-tls-configmap.yaml
  - nfs-server-tls.yaml
  - nfsstorageclass.yaml
