run:
  timeout: 10m

issues:
  exclude:
    - ST1005.*
    - "should not use dot imports"
    - "don't use an underscore in package name"
    - "exported: .*"

linters-settings:
  container:
    exclude-rules:
      liveness-probe:
        - kind: Deployment
          name: csi-controller
          container: snapshotter
        - kind: Deployment
          name: csi-controller
          container: resizer
        - kind: Deployment
          name: csi-controller
          container: attacher
        - kind: Deployment
          name: csi-controller
          container: provisioner
      readiness-probe:
        - kind: Deployment
          name: csi-controller
          container: snapshotter
        - kind: Deployment
          name: csi-controller
          container: resizer
        - kind: Deployment
          name: csi-controller
          container: attacher
        - kind: Deployment
          name: csi-controller
          container: provisioner

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/deckhouse)

linters:
  disable-all: true
  enable:
    - dogsled
    - errcheck
    - gci
    - gocritic
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - whitespace
    - copyloopvar
