---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhooks
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "webhooks")) | nindent 2 }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: d8:{{ .Chart.Name }}:webhooks
  {{- include "helm_lib_module_labels" (list . (dict "app" "webhooks")) | nindent 2 }}
rules:
  - apiGroups:
      - deckhouse.io
    resources:
      - moduleconfigs
    verbs:
      - get
      - watch
      - update
      - list
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: d8:{{ .Chart.Name }}:webhooks
  {{- include "helm_lib_module_labels" (list . (dict "app" "webhooks")) | nindent 2 }}
subjects:
  - kind: ServiceAccount
    name: webhooks
    namespace: d8-{{ .Chart.Name }}
roleRef:
  kind: ClusterRole
  name: d8:{{ .Chart.Name }}:webhooks
  apiGroup: rbac.authorization.k8s.io
