{{- define "kube_scheduler_resources" }}
cpu: 10m
memory: 30Mi
{{- end }}

{{- define "csi_nfs_scheduler_extender_resources" }}
cpu: 10m
memory: 25Mi
{{- end }}

{{- if .Values.csiNfs.internal.shedulerExtenderEnabled }}
{{- if or (or (hasPrefix "dev" .Values.global.deckhouseVersion) (hasSuffix "dev" .Values.global.deckhouseVersion)) (semverCompare ">=1.64" .Values.global.deckhouseVersion) }}

{{- $kubeVersion := semver .Values.global.discovery.kubernetesVersion -}}
{{- if (.Values.global.enabledModules | has "vertical-pod-autoscaler-crd") }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: csi-nfs-scheduler-extender
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "csi-nfs-scheduler-extender")) | nindent 2 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: csi-nfs-scheduler-extender
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: kube-scheduler
      minAllowed:
        {{- include "kube_scheduler_resources" . | nindent 8 }}
      maxAllowed:
        memory: 60Mi
        cpu: 20m
    - containerName: csi-nfs-scheduler-extender
      minAllowed:
        {{- include "csi_nfs_scheduler_extender_resources" . | nindent 8 }}
      maxAllowed:
        memory: 40Mi
        cpu: 20m
{{- end }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: csi-nfs-scheduler-extender
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "csi-nfs-scheduler-extender" )) | nindent 2 }}
spec:
  minAvailable: {{ include "helm_lib_is_ha_to_value" (list . 1 0) }}
  selector:
    matchLabels:
      app: csi-nfs-scheduler-extender
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-nfs-scheduler-extender
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "csi-nfs-scheduler-extender" )) | nindent 2 }}
spec:
  {{- include "helm_lib_deployment_strategy_and_replicas_for_ha" . | nindent 2 }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: csi-nfs-scheduler-extender
  template:
    metadata:
      labels:
        app: csi-nfs-scheduler-extender
    spec:
      {{- include "helm_lib_priority_class" (tuple . "system-cluster-critical") | nindent 6 }}
      {{- include "helm_lib_node_selector" (tuple . "system") | nindent 6 }}
      {{- include "helm_lib_tolerations" (tuple . "system") | nindent 6 }}
      {{- include "helm_lib_module_pod_security_context_run_as_user_nobody" . | nindent 6 }}
      {{- include "helm_lib_pod_anti_affinity_for_ha" (list . (dict "app" "csi-nfs-scheduler-extender")) | nindent 6 }}
      imagePullSecrets:
        - name: {{ .Chart.Name }}-module-registry
      containers:
        - name: csi-nfs-scheduler-extender
          {{- include "helm_lib_module_container_security_context_read_only_root_filesystem_capabilities_drop_all" . | nindent 10 }}
          image: {{ include "helm_lib_module_image" (list . "csiNfsSchedulerExtender") }}
          imagePullPolicy: IfNotPresent
          args:
            - csi-nfs-scheduler-extender
            - --config=/etc/csi-nfs-scheduler-extender/scheduler-extender-config.yaml
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          volumeMounts:
          - name: scheduler-extender-config
            mountPath: /etc/csi-nfs-scheduler-extender
            readOnly: true
          - name: scheduler-extender-certs
            mountPath: /etc/csi-nfs-scheduler-extender/certs
            readOnly: true
          resources:
            requests:
              {{- include "helm_lib_module_ephemeral_storage_only_logs" . | nindent 14 }}
              {{- if not ( .Values.global.enabledModules | has "vertical-pod-autoscaler-crd") }}
              {{- include "csi_nfs_scheduler_extender_resources" . | nindent 14 }}
              {{- end }}
          ports:
          - containerPort: 8099
            protocol: TCP
      volumes:
      - name: scheduler-extender-config
        configMap:
          defaultMode: 420
          name: csi-nfs-scheduler-extender
      - name: scheduler-extender-certs
        secret:
            secretName: scheduler-extender-https-certs
      serviceAccountName: csi-nfs-scheduler-extender

{{- end }}
{{- end }}
