{{- if .Values.csiNfs.internal.shedulerExtenderEnabled }}
{{- if or (or (hasPrefix "dev" .Values.global.deckhouseVersion) (hasSuffix "dev" .Values.global.deckhouseVersion)) (semverCompare ">=1.64" .Values.global.deckhouseVersion) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: scheduler-extender-https-certs
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "csi-nfs-scheduler-extender")) | nindent 2 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ .Values.csiNfs.internal.customSchedulerExtenderCert.ca | b64enc }}
  tls.crt: {{ .Values.csiNfs.internal.customSchedulerExtenderCert.crt | b64enc }}
  tls.key: {{ .Values.csiNfs.internal.customSchedulerExtenderCert.key | b64enc }}

{{- end }}
{{- end }}
