{{- $ns := .Values.csiNfs.nodeSelector | default dict }}
{{- if or (ne (len $ns) 1) (ne (index $ns "kubernetes.io/os") "linux") }}
{{- if or (eq "dev" .Values.global.deckhouseVersion) (semverCompare ">=1.64" .Values.global.deckhouseVersion) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: scheduler-extender-https-certs
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "csi-nfs-scheduler-extender")) | nindent 2 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ .Values.csiNfs.internal.customSchedulerExtenderCert.ca }}
  tls.crt: {{ .Values.csiNfs.internal.customSchedulerExtenderCert.crt }}
  tls.key: {{ .Values.csiNfs.internal.customSchedulerExtenderCert.key }}

{{- end }}
{{- end }}
