type: object
properties:
  logLevel:
    type: string
    enum:
      - ERROR
      - WARN
      - INFO
      - DEBUG
      - TRACE
    description: Module log level.
    default: DEBUG
  v3support:
    type: boolean
    default: false
    description: NFS version v3 support.
  tlsParameters:
    type: object
    default: {}
    description: RPC-with-TLS (RFC 9289) configuration.
    properties:
      ca:
        type: string
        description: Root certificate in PEM format, encoded in Base64, which can be used to verify the NFS server certificate.
      mtls:
        type: object
        default: {}
        description: Configuration of the client certificate verification mode by the NFS server.
        properties:
          clientCert:
            type: string
            description: Client certificate in PEM format, encoded in Base64.
          clientKey:
            type: string
            description: Client key in PEM format, encoded in Base64.
