type: object
properties:
  logLevel:
    type: string
    enum:
      - ERROR
      - WARN
      - INFO
      - DEBUG
      - TRACE
    description: Module log level
    default: DEBUG
  v3support:
    type: boolean
    default: false
    description: NFS version v3 support
