type: object
properties:
  logLevel:
    description: Уровень логирования модуля.
  v3support:
    description: Поддержка NFS версии v3. После включения этого параметра на узлы будет установлен rpc-statd. При отключении этого параметра он НЕ будет удален с узлов.
