type: object
properties:
  logLevel:
    description: Уровень логирования модуля.
  v3support:
    description: Поддержка NFS версии v3. После включения этого параметра на узлы будет установлен rpc-statd. При отключении этого параметра он НЕ будет удален с узлов.
  tlsParameters:
    description: Настройка RPC-with-TLS (RFC 9289).
    properties:
      ca:
        description: Корневой сертификат в формате PEM, которым можно проверить сертификат nfs сервера, закодированный в Base64.
      mtls:
        description: Настройка режима проверки nfs сервером сертифката клиента.
      properties:
        clientCert:
          description: Клиентский сертификат в формате PEM, закодированный в Base64.
        clientKey:
          description: Клиентский ключ в формате PEM, закодированный в Base64.
