apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    heritage: deckhouse
    module: csi-nfs
    rbac.deckhouse.io/aggregate-to-csi-nfs-as: viewer
    rbac.deckhouse.io/kind: manage
    rbac.deckhouse.io/level: module
    rbac.deckhouse.io/namespace: d8-csi-nfs
  name: d8:manage:permission:subsystem:csi-nfs:view_resources
rules:
  - apiGroups:
      - storage.deckhouse.io
    resources:
      - nfsstorageclasses
    verbs:
      - get
      - list
      - watch
