apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nfsstorageclasses.storage.deckhouse.io
  labels:
    heritage: deckhouse
    module: storage
    backup.deckhouse.io/cluster-config: "true"
spec:
  group: storage.deckhouse.io
  scope: Cluster
  names:
    plural: nfsstorageclasses
    singular: nfsstorageclass
    kind: NFSStorageClass
    shortNames:
      - nsc
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: |
            NFSStorageClass is a Kubernetes Custom Resource that defines a configuration for a Kubernetes Storage class.
          required:
            - spec
          properties:
            spec:
              type: object
              description: |
                Defines a Kubernetes Storage class configuration.
              required:
                - connection
                - reclaimPolicy
                - volumeBindingMode
              properties:
                connection:
                  type: object
                  x-kubernetes-validations:
                    - rule: self == oldSelf
                      message: Value is immutable.
                  description: |
                    Defines a Kubernetes Storage class configuration.
                  required:
                    - host
                    - share
                    - nfsVersion
                  properties:
                    host:
                      type: string
                      x-kubernetes-validations:
                        - rule: self == oldSelf
                          message: Value is immutable.
                      description: |
                        NFS server host
                      minLength: 1
                    share:
                      type: string
                      x-kubernetes-validations:
                        - rule: self == oldSelf
                          message: Value is immutable.
                      description: |
                        NFS server share path
                      minLength: 1
                    nfsVersion:
                      type: string
                      x-kubernetes-validations:
                        - rule: self == oldSelf
                          message: Value is immutable.
                      description: |
                        NFS server version
                      enum:
                        - "3"
                        - "4.1"
                        - "4.2"
                mountOptions:
                  type: object
                  description: |
                    Storage class mount options
                  properties:
                    mountMode:
                      type: string
                      description: |
                        NFS share mount mode
                      enum:
                        - hard
                        - soft
                    timeout:
                      type: integer
                      description: |
                        NFS server timeout
                      minimum: 1
                    retransmissions:
                      type: integer
                      description: |
                        NFS retries before fail
                      minimum: 1
                    readOnly:
                      type: boolean
                      description: |
                        Share read-only flag
                chmodPermissions:
                  type: string
                  description: |
                    chmod rights for PVs subdirectory
                  pattern: '^[0-7]{3,4}$'
                reclaimPolicy:
                  type: string
                  x-kubernetes-validations:
                    - rule: self == oldSelf
                      message: Value is immutable.
                  description: |
                    The storage class's reclaim policy. Might be:
                    - Delete (If the Persistent Volume Claim is deleted, deletes the Persistent Volume and its associated storage as well)
                    - Retain (If the Persistent Volume Claim is deleted, remains the Persistent Volume and its associated storage)
                  enum:
                    - Delete
                    - Retain
                volumeBindingMode:
                  type: string
                  x-kubernetes-validations:
                    - rule: self == oldSelf
                      message: Value is immutable.
                  description: |
                    The storage class's volume binding mode. Might be Immediate or WaitForFirstConsumer
                  enum:
                    - Immediate
                    - WaitForFirstConsumer
                nodeSelector:
                  type: object
                  description: |
                    Node selector to specify rules for selecting nodes where Persistent Volumes (PVs) created by this StorageClass are allowed to connect. Combines simple label matches and advanced matching expressions.
                    If this parameter is omitted, NFS shares can be mounted on any node in the cluster running the `Linux` OS.
                  properties:
                    matchLabels:
                      type: object
                      description: |
                        A map of labels that must match exactly with the labels of a node. Nodes that do not match any of the specified labels will be excluded.
                      additionalProperties:
                        type: string
                    matchExpressions:
                      type: array
                      description: |
                        A list of advanced node selector requirements. Each requirement specifies a key, an operator, and optional values for filtering nodes based on their labels or other fields.
                      items:
                        type: object
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                            enum:
                              - In
                              - NotIn
                              - Exists
                              - DoesNotExist
                          values:
                            type: array
                            items:
                              type: string
            status:
              type: object
              description: |
                Displays current information about the Storage Class.
              properties:
                phase:
                  type: string
                  description: |
                    The Storage class current state. Might be: 
                    - Failed (if the controller received incorrect resource configuration or some errors occurred during the operation)
                    - Create (if everything went fine)
                  enum:
                    - Failed
                    - Created
                reason:
                  type: string
                  description: |
                    Additional information about the current state of the Storage Class.
      subresources:
        status: {}
      additionalPrinterColumns:
        - jsonPath: .status.phase
          name: Phase
          type: string
        - jsonPath: .status.reason
          name: Reason
          type: string
          priority: 1
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
          description: The age of this resource
