apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nfsstorageclasses.storage.deckhouse.io
  labels:
    heritage: deckhouse
    module: storage
spec:
  group: storage.deckhouse.io
  scope: Cluster
  names:
    plural: nfsstorageclasses
    singular: nfsstorageclass
    kind: NFSStorageClass
    shortNames:
      - nsc
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: |
            NFSStorageClass is a Kubernetes Custom Resource that defines a configuration for a Kubernetes Storage class.
          required:
            - spec
          properties:
            spec:
              type: object
              description: |
                Defines a Kubernetes Storage class configuration.
              required:
                - server
              properties:
                server:
                  type: object
                  description: |
                    Defines a Kubernetes Storage class configuration.
                  required:
                    - host
                    - share
                    - nfsVersion
                  properties:
                    host:
                      type: string
                      x-kubernetes-validations:
                        - rule: self == oldSelf
                          message: Value is immutable.
                      description: |
                        NFS server host
                    share:
                      type: string
                      x-kubernetes-validations:
                        - rule: self == oldSelf
                          message: Value is immutable.
                      description: |
                        NFS server share path
                    nfsVersion:
                      type: string
                      x-kubernetes-validations:
                        - rule: self == oldSelf
                          message: Value is immutable.
                      description: |
                        NFS server version
                      enum:
                        - "3"
                        - "4.1"
                        - "4.2"
                options:
                  type: object
                  description: |
                    Storage class mount options
                  properties:
                    mountMode:
                      type: string
                      description: |
                        NFS share mount mode
                      enum:
                        - hard
                        - soft
                    timeout:
                      type: integer
                      description: |
                        NFS server timeout
                    retransmissions:
                      type: integer
                      description: |
                        NFS retries before fail
                    readOnly:
                      type: boolean
                      description: |
                        Share read-only flag
                chmodPermissions:
                  type: string
                  description: |
                    chmod rights for PVs subdirectory
                reclaimPolicy:
                  type: string
                  x-kubernetes-validations:
                    - rule: self == oldSelf
                      message: Value is immutable.
                  description: |
                    The storage class's reclaim policy. Might be:
                    - Delete (If the Persistent Volume Claim is deleted, deletes the Persistent Volume and its associated storage as well)
                    - Retain (If the Persistent Volume Claim is deleted, remains the Persistent Volume and its associated storage)
                  enum:
                    - Delete
                    - Retain
                volumeBindingMode:
                  type: string
                  x-kubernetes-validations:
                    - rule: self == oldSelf
                      message: Value is immutable.
                  description: |
                    The storage class's volume binding mode. Might be Immediate or WaitForFirstConsumer
                  enum:
                    - Immediate
                    - WaitForFirstConsumer
            status:
              type: object
              description: |
                Displays current information about the Storage Class.
              properties:
                phase:
                  type: string
                  description: |
                    The Storage class current state. Might be: 
                    - Failed (if the controller received incorrect resource configuration or some errors occurred during the operation)
                    - Create (if everything went fine)
                  enum:
                    - Failed
                    - Created
                reason:
                  type: string
                  description: |
                    Additional information about the current state of the Storage Class.
      subresources:
        status: {}
