name: Go linter for images

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Go linter for images
    runs-on: [self-hosted, regular]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.61.0

      - name: Run Go lint
        run: |
          basedir=$(pwd)
          failed='false'
          for i in $(find images -type f -name go.mod);do
            dir=$(echo $i | sed 's/go.mod$//')
            echo "Running linter in $dir"
            cd $dir
            # check all editions
            for edition in EE CE ;do
              golangci-lint run --build-tags $MODULE_EDITION
              if [ $? -ne 0 ]; then
                echo "Linter failed in $dir"
                failed='true'
              fi
            done
            cd $basedir
          done
          if [ $failed == 'true' ]; then
            exit 1
          fi
