name: Go linter for images

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_dev:
    uses: ./.github/workflows/build_dev.yml
    secrets: inherit
  test:
    name: Go linter for images
    runs-on: [self-hosted, regular]
    needs: [build_dev]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.61.0

      - name: Run Go lint
        run: |
          # TODO use github actions/download-artifact and actions/upload-artifact
          if [ -f .github/MODULE_EDITION.env.tmp ];then
            source .github/MODULE_EDITION.env.tmp
            rm -f .github/MODULE_EDITION.env.tmp
          else
            echo "Can`t find file .github/MODULE_EDITION.env.tmp. Export MODULE_EDITION=EE".
            export MODULE_EDITION=EE
          fi

          basedir=$(pwd)
          failed='false'
          for dir in $(find images -type d); do
            if ls $dir/go.mod &> /dev/null; then
              echo "Running linter in $dir"
              cd $dir
              golangci-lint run --build-tags $MODULE_EDITION
              if [ $? -ne 0 ]; then
                echo "Linter failed in $dir"
                failed='true'
              fi
            cd $basedir
            fi
          done
          if [ $failed == 'true' ]; then
            exit 1
          fi
