name: Trivy images check

on:
  pull_request:
    types: [opened, reopened, labeled, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release_branch:
        description: 'release branch name, example: release-1.68'
        required: false

jobs:
  build_dev:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/build_dev.yml
    secrets: inherit
  cve_scan_on_pr:
    if: github.event_name == 'pull_request'
    name: Trivy images check
    runs-on: [self-hosted, regular]
    needs: [build_dev]
    steps:
      - uses: actions/checkout@v4
      - uses: deckhouse/modules-actions/cve_scan@cve_scan_ci
        with:
          IMAGE: ${{ vars.DEV_MODULE_SOURCE }}/${{ vars.MODULE_NAME }}
          TAG: pr${{ github.event.number }}
          MODULE_NAME: ${{ vars.MODULE_NAME }}
          DD_URL: ${{secrets.DEFECTDOJO_HOST}}
          DD_TOKEN: ${{secrets.DEFECTDOJO_API_TOKEN}}
          TRIVY_REGISTRY: ${{ vars.PROD_REGISTRY }}
          TRIVY_REGISTRY_USER: ${{ vars.PROD_MODULES_REGISTRY_LOGIN }}
          TRIVY_REGISTRY_PASSWORD: ${{ secrets.PROD_MODULES_REGISTRY_PASSWORD }}
          TRIVY_TOKEN: ${{secrets.FOX_ACCESS_TOKEN}}
          DECKHOUSE_PRIVATE_REPO: ${{secrets.DECKHOUSE_PRIVATE_REPO}}
  cve_scan:
    if: github.event_name != 'pull_request'
    name: Trivy images check
    runs-on: [self-hosted, regular]
    steps:
      - uses: actions/checkout@v4
      - name: Sets env vars for manual run
        run: |
          echo "MODULE_IMAGE_TAG=${{ github.event.inputs.release_branch || 'main' }}" >> $GITHUB_ENV
        if: github.event_name != 'workflow_dispatch'
      - uses: deckhouse/modules-actions/cve_scan@cve_scan_ci
        with:
          IMAGE: ${{ vars.DEV_MODULE_SOURCE }}/${{ vars.MODULE_NAME }}
          TAG: ${{ env.MODULE_IMAGE_TAG || 'main' }}
          MODULE_NAME: ${{ vars.MODULE_NAME }}
          DD_URL: ${{secrets.DEFECTDOJO_HOST}}
          DD_TOKEN: ${{secrets.DEFECTDOJO_API_TOKEN}}
          TRIVY_REGISTRY: ${{ vars.PROD_REGISTRY }}
          TRIVY_REGISTRY_USER: ${{ vars.PROD_MODULES_REGISTRY_LOGIN }}
          TRIVY_REGISTRY_PASSWORD: ${{ secrets.PROD_MODULES_REGISTRY_PASSWORD }}
          TRIVY_TOKEN: ${{secrets.FOX_ACCESS_TOKEN}}
          DECKHOUSE_PRIVATE_REPO: ${{secrets.DECKHOUSE_PRIVATE_REPO}}
