{{- if .Values.csiNfs.tlsParameters }}
{{/*  File /etc/client.crt: expected mode 644 - because of this message in the tlshd container log, I did not create a separate ConfigMap. */}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tlshd-conf
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
data:
  tlshd.conf: |
    #
    # Copyright (c) 2022 Oracle and/or its affiliates.
    #
    # This file is part of ktls-utils.
    #
    # ktls-utils is free software; you can redistribute it and/or
    # modify it under the terms of the GNU General Public License as
    # published by the Free Software Foundation; version 2.
    #
    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
    # General Public License for more details.
    #
    # You should have received a copy of the GNU General Public License
    # along with this program; if not, write to the Free Software
    # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
    # 02110-1301, USA.
    #
    # See tlshd.conf(5) for details.
    #

    [debug]
    loglevel=0
    tls=0
    nl=0

    [authenticate]
    #keyrings= <keyring>;<keyring>;<keyring>

    [authenticate.client]
    x509.truststore=/etc/ca.crt
    x509.certificate=/etc/client.crt
    x509.private_key=/etc/client.key

    [authenticate.server]
    #x509.truststore= <pathname>
    #x509.certificate= <pathname>
    #x509.private_key= <pathname>

  {{- if .Values.csiNfs.tlsParameters.ca }}
  ca.crt: |
    {{- .Values.csiNfs.tlsParameters.ca | b64dec | nindent 4 }}
  {{- end }}

  {{- if .Values.csiNfs.tlsParameters.mtls.clientCert }}
  client.crt: |
    {{- .Values.csiNfs.tlsParameters.mtls.clientCert | b64dec | nindent 4 }}
  {{- end }}

  {{- if .Values.csiNfs.tlsParameters.mtls.clientKey }}
  client.key: |
    {{- .Values.csiNfs.tlsParameters.mtls.clientKey | b64dec | nindent 4 }}
  {{- end }}

{{- end }}
