{{- include "helm_lib_csi_controller_rbac" . }}

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: csi-node
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "csi-nfs-csi-node")) | nindent 2 }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: d8:{{ .Chart.Name }}:csi-node
  {{- include "helm_lib_module_labels" (list . (dict "app" "csi-nfs-csi-node")) | nindent 2 }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: d8:{{ .Chart.Name }}:csi-node
  {{- include "helm_lib_module_labels" (list . (dict "app" "csi-nfs-csi-node")) | nindent 2 }}
subjects:
  - kind: ServiceAccount
    name: csi-node
    namespace: d8-{{ .Chart.Name }}
roleRef:
  kind: ClusterRole
  name: d8:{{ .Chart.Name }}:csi-node
  apiGroup: rbac.authorization.k8s.io

