{{- if (.Values.global.enabledModules | has "snapshot-controller") }}
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-nfs-snapshot-class
  {{- include "helm_lib_module_labels" (list . (dict "app" "csi-nfs")) | nindent 2 }}
driver: nfs.csi.k8s.io
deletionPolicy: Delete
{{- end }}
